// Generated by gencpp from file car_msgs/MotorsControl.msg
// DO NOT EDIT!


#ifndef CAR_MSGS_MESSAGE_MOTORSCONTROL_H
#define CAR_MSGS_MESSAGE_MOTORSCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_msgs
{
template <class ContainerAllocator>
struct MotorsControl_
{
  typedef MotorsControl_<ContainerAllocator> Type;

  MotorsControl_()
    : left(0)
    , right(0)  {
    }
  MotorsControl_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_type;
  _left_type left;

   typedef int16_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::car_msgs::MotorsControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_msgs::MotorsControl_<ContainerAllocator> const> ConstPtr;

}; // struct MotorsControl_

typedef ::car_msgs::MotorsControl_<std::allocator<void> > MotorsControl;

typedef boost::shared_ptr< ::car_msgs::MotorsControl > MotorsControlPtr;
typedef boost::shared_ptr< ::car_msgs::MotorsControl const> MotorsControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_msgs::MotorsControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_msgs::MotorsControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_msgs::MotorsControl_<ContainerAllocator1> & lhs, const ::car_msgs::MotorsControl_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_msgs::MotorsControl_<ContainerAllocator1> & lhs, const ::car_msgs::MotorsControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_msgs::MotorsControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_msgs::MotorsControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::MotorsControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::MotorsControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::MotorsControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::MotorsControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_msgs::MotorsControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09d1b2323a1aeae9343e81809a820b60";
  }

  static const char* value(const ::car_msgs::MotorsControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09d1b2323a1aeae9ULL;
  static const uint64_t static_value2 = 0x343e81809a820b60ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_msgs::MotorsControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_msgs/MotorsControl";
  }

  static const char* value(const ::car_msgs::MotorsControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_msgs::MotorsControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PWM control for left and right motors\n"
"int16 left\n"
"int16 right\n"
;
  }

  static const char* value(const ::car_msgs::MotorsControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_msgs::MotorsControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorsControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_msgs::MotorsControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_msgs::MotorsControl_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MSGS_MESSAGE_MOTORSCONTROL_H
