<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
    <xacro:property name="wheel_thickness" value="0.06" />
    <xacro:property name="wheel_radius" value="0.063" />
    <xacro:property name="roller_radius" value="0.1075" />
    <xacro:property name="body_length" value="0.380" />
    <xacro:property name="body_width" value="0.120" />
    <xacro:property name="body_height" value="0.072" />
    <xacro:property name="mass" value="3.3" />
    <xacro:property name="wheel_mass" value="1e-5" />
    <xacro:property name="pi" value="3.1415" />

    <!-- Import all Gazebo-customization elements, including Gazebo colors -->
    <xacro:include filename="$(find my_urdf)/urdf/robot.gazebo" />

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="gray">
        <color rgba="0.7 0.7 0.7 1"/>
    </material>

    <link name="world"/>

    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 ${body_height/2}"/>
            <geometry>
                <mesh filename="package://my_urdf/meshes/chassis.dae" scale="${body_length*2.3} ${body_width*3.6} ${body_height*5.71}"/> 
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${body_height/2}"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <inertial>
            <!-- <origin xyz="0.0 0.0 ${body_height/2+0.09}"/> -->
            <mass value="3.3" /> <!-- mass in kg -->
            <inertia ixx="0.005386" ixy="0.000000" ixz="0.00000"
                                        iyy="0.041136" iyz="0.00000"
                                                       izz="0.04367"/>
            </inertial>
        
    </link>

    <xacro:macro name="wheel" params="prefix color radius thickness reflect">
        <joint name="joint_${prefix}_wheel_to_base" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${-body_length/4} ${reflect*(body_width/2+thickness/2)} 0"/>
            <axis xyz = "0 1 0" />
            <dynamics damping ="0.002" />
        </joint>
        <link name="${prefix}_wheel">
            <visual>
                <origin rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
                <material name="${color}"/>
            </visual>
            <collision>
                <origin xyz="0 ${thickness/2 + 0.002} 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.150"/>
                <inertia ixx="0.00019384" ixy="0.00000000" ixz="00000000"
                                          iyy="0.00019384" iyz="00000000"
                                                           izz="0.004725"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel prefix="left" color="black" radius="${wheel_radius}" thickness="${wheel_thickness}" reflect="1"/>
    <xacro:wheel prefix="right" color="blue" radius="${wheel_radius}" thickness="${wheel_thickness}" reflect="-1"/>


    

    <joint name="roller_wheel_horizontal_to_base" type="continuous">
        <parent link="base_link"/>
        <child link="roller_wheel_horizontal"/>
        <origin xyz="${body_length/2 - wheel_radius / 2} 0.0 -${wheel_radius / 2}"/>
		<axis xyz = "0 0 1" />
		<dynamics damping ="0.002" />
    </joint>
    <link name="roller_wheel_horizontal">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius / 2}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius / 4}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.150"/>
            <inertia ixx="0.00019384" ixy="0.00000000" ixz="00000000"
                                        iyy="0.00019384" iyz="00000000"
                                                        izz="0.004725"/>
        </inertial>
    </link>



    <joint name="roller_wheel_vertical_to_base" type="continuous">
        <parent link="roller_wheel_horizontal"/>
        <child link="roller_wheel_vertical"/>
		<axis xyz = "1 0 0" />
		<dynamics damping ="0.002" />
    </joint>    
    <link name="roller_wheel_vertical">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius / 2}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_radius / 4}"/>
            </geometry>
        </collision>
        <inertial>
            <origin rpy="${pi/2} 0.0 0.0"/>
            <mass value="0.15" />
            <inertia  ixx="0.0001" ixy="0" ixz="0"
                    iyy="0.0001" iyz="0"
                    izz="0.0001" />
        </inertial>
    </link>

    <!-- <link name="chassis">
        <visual>
            <origin xyz="0 0 0.3"/>
            <geometry>
                <mesh filename="package://my_urdf/meshes/chassis.dae"/>
            </geometry>
        </visual>
    </link>
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
    </joint> -->

    <!-- Hokuyo Laser -->
    <joint name="hokuyo_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="hokuyo_link"/>
    </joint>

    <link name="hokuyo_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://my_urdf/meshes/hokuyo.dae"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>
</robot>